### ISSUE TITLE
Incorrect link on user library

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-user-library#79]
On the the GO User Library there is a link, which is not working. 
 
[IFRC GO User Library](https://go-user-library.ifrc.org/brand-design/brand)
 
The link to the “Download IFRC Brand Guidelines” is currently:
[https://go-user-library.ifrc.org/brand-design/https://github.com/IFRCGo/IFRC-Icons](https://go-user-library.ifrc.org/brand-design/https:/github.com/IFRCGo/IFRC-Icons)

The correct page to download the package: https://www.dropbox.com/sh/v9scmzq69i2bdk4/AABICdMR9QEqA9c3TFC7YSmda?dl=0

**Comment by szabozoltan69** [comment]
Fixed.
Pls. check https://go-user-library.ifrc.org/brand-design/brand
